# Generated by Django 3.2.9 on 2021-11-27 06:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('bookname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(max_length=2500)),
                ('node_id', models.CharField(max_length=100)),
                ('branch_name', ckeditor.fields.RichTextField(default='Start', max_length=700)),
                ('path', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
                ('book_id', models.IntegerField()),
            ],
        ),
    ]
